---
title: "Econ 343 Logit Regression - Ch 17 (sec. 1) Example and re-do Ch 7 C8"
output:
  pdf_document: default
  html_document:
    df_print: paged
  word_document: default
  beamer_presentation: default
---

```{r setup, include=FALSE}
#
# ===>> SETUP - this r-chunk does not usually need to be changed by the student.
#
# The following packages cover all of the commands that will be used in this class,
# as well as the files from the Wooldridge textbook.
# 
# For any assignment, you simply start by making a copy of this file and add the R chunks and
# text as needed below this setup chunk. 
#
# Note that these packages have been carefully selected to create a toolkit that is ideally
# suited for economic and business analysis. You might find it useful to keep this template and
# set of packages for future data analysis projects.
#
library(readr)      # for reading in .csv files
library(tidyverse)  # data wrangling
library(dplyr)      # for filter and select commands. etc.
library(wooldridge) # datasets in the textbook
library(stats)      # basic statistic commands
library(DataExplorer) # nice commands to learn about a new data set
library(stargazer)  # nice regression output
library(ggformula)  # easy graphing interface for ggplot
library(mosaic)     # accompanies ggformula
library(expss)      # apply_labels() cro()
library(scales)     # to format inline r as currency
library(AER)        # data and commands specific to econometrics
library(car)        # for linearhypothesis tests lht(), predict() hccm() heterosced.
library(lmtest)     # post-reg tests coeftest()
library(effects)    # to plot effects of one regressor, holding all others constant
library(visualize)  # to visualize hypothesis test p-values
library(dynlm)      # lm commands for time series data
library(plm)        # lm commands for panel data
library(kableExtra)

options(scipen=999)
options(digits=4)   # limits number of decimals to 4 when printing
knitr::opts_chunk$set(echo = TRUE) # TRUE = commands in r chunks to be echoed in outfile
```

# Ch. 17 (sec. 1) Example 1: LPM vs. Logit 

## Estimate linear probability model

```{r}

mydata <- mroz


lpm1 <- lm(inlf ~ nwifeinc + educ + exper + I(exper^2) + age + kidslt6 + kidsge6,data=mydata)

# Regression table with correction for heteroskedasticity:
lpm1.hccm <- coeftest(lpm1,vcov=hccm)

stargazer(lpm1,lpm1.hccm,type = "text")

# Predictions 
xpred <- list(nwifeinc=c(45),educ=c(16),exper=c(5),
              age=c(30),kidslt6=c(1),kidsge6=c(0))

predict(lpm1,xpred)


```

## Estimate Logit
```{r}
logit.1 <- glm(inlf ~ nwifeinc + educ + exper + I(exper^2) + age + kidslt6 + kidsge6,
               data=mydata,family="binomial")

# Predictions from linear probability, probit and logit model:
# (run 17-1-1.R through 17-1-4.R first to define the variables!)
predict(lpm1,  xpred,type = "response")
predict(logit.1, xpred,type = "response")
```

## Compare Average Partial Effects
```{r}


# Calculation of linear index at individual values:
xb.logit <- predict(logit.1)

# APE factors = average(g(xb))
factor.log <- mean( dlogis(xb.logit) )


# average partial effects = beta*factor:
APE.lpm1 <- coef(lpm1) * 1
APE.logit.1 <- coef(logit.1) * factor.log

# Table of APEs
cbind(APE.lpm1, APE.logit.1)

```


# Ch. 7 HW C8 LPM vs. Logit 

## Estimate linear probability model

```{r}

mydata.nomissings <- na.omit(loanapp)

lpm2 <- lm(approve ~ white + hrat + obrat + I(white*(obrat-32)) + loanprc + unem + male +
               married + dep + sch + 
               cosign + chist + pubrec + mortlat1 + + mortlat2 + vr, data=mydata.nomissings)

# Regression table with correction for heteroskedasticity:
lpm2.hccm <- coeftest(lpm2,vcov=hccm)

stargazer(lpm2,lpm2.hccm,type = "text")

```

## Estimate Logit
```{r}
logit.2 <- glm(approve ~ white + hrat + obrat + I(white*(obrat-32)) + loanprc + unem + male +
               married + dep + sch + 
               cosign + chist + pubrec + mortlat1 + + mortlat2 + vr, data=mydata.nomissings,family="binomial")

#predict(lpm2, xpred, type = "response")
#predict(logit.2, xpred,type = "response")
```

## Compare Average Partial Effects
```{r}


# Calculation of linear index at individual values:
xb.logit <- predict(logit.2)

# APE factors = average(g(xb))
factor.log <- mean( dlogis(xb.logit) )


# average partial effects = beta*factor:
APE.lpm2 <- coef(lpm2) * 1
APE.logit.2 <- coef(logit.2) * factor.log

# Table of APEs
cbind(APE.lpm2, APE.logit.2)

```